<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP2EBH" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Prof. Dr. Gudrun Görlitz, Sandra Kaltofen" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="discipline" content="Medieninformatik Online Bachelor" />
<meta name="creation_time" content="20100915" />
<meta name="learning_time" content="180" />
<meta name="language" content="DE" />
<meta name="keywords" content="Ereignisbehandlung" />
<meta name="description" content="" />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="EBH" />
<meta name="unit_dir" content="GP2EBH" />
<meta name="unit" content="Ereignisbehandlung" />
<meta name="unit_number" content="27" />
<meta name="pdf_title" content="Ereignisbehandlung" />
<meta name="version" content="2.0" />
<meta name="generator" content="Beuth-Toolbox 2.0" />
<meta name="revisiondate" content="2010-09-10" />
<meta name="year" content="2010" />