<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP22DG" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Prof. Dr. Gudrun Görlitz" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="version" content="1.3" />
<meta name="discipline" content="Medieninformatik Online Bachelor" />
<meta name="creation_time" content="20020204" />
<meta name="learning_time" content="180" />
<meta name="language" content="DE" />
<meta name="keywords" content="2D-Grafik" />
<meta name="description" content=" In dieser Lerneinheit geht es zunächst um die Grundlagen der Bildschirmgrafik. Sie werden passive Bildschirmobjekte im Grafik-Fenster darstellen. Darauf aufbauend wird in den nachfolgenden Lerneinheiten die Programmierung interaktiver grafischer Benutzeroberflächen im Zusammenhang mit der Ereignisverarbeitung in Java vermittelt." />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="2DG" />	
<meta name="unit_dir" content="GP22DG" />
<meta name="unit" content="2D Grafik" />
<meta name="unit_number" content="25" />
<meta name="pdf_title" content="2D_Grafik" />
<meta name="generator" content="Beuth-Toolbox 2.0" />
<meta name="revisiondate" content="2002-02-04" />
<meta name="year" content="2002" />