<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP2XML" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Sandra Kaltofen" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="discipline" content="Medieninformatik Online Bachelor" />
<meta name="creation_time" content="" />
<meta name="learning_time" content="180" />
<meta name="language" content="DE" />
<meta name="keywords" content="XML" />
<meta name="description" content="" />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="XML" />
<meta name="unit_dir" content="GP2XML" />
<meta name="unit" content="Java und XML">
<meta name="unit_number" content="09" />
<meta name="pdf_title" content="JavaUndXML">
<meta name="version" content="1.0" />
<meta name="generator" content="BHT-Toolbox 2.0" />
<meta name="revisiondate" content="2010-03-15" />
<meta name="year" content="2009" />