<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP2DUD" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Prof. Dr. Gudrun Görlitz, Prof. Dr. A. Merceron" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="version" content="1.3" />
<meta name="discipline" content="Medieninformatik Online Bachelor" />
<meta name="creation_time" content="20020405" />
<meta name="learning_time" content="180" />
<meta name="language" content="DE" />
<meta name="keywords" content="Dateien, Datenstrom" />
<meta name="description" content="" />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="DUD" />
<meta name="unit_dir" content="GP2DUD" />
<meta name="unit" content="Dateien und Datenströme" />
<meta name="unit_number" content="02" />
<meta name="pdf_title" content="DateienUndDatenstroeme" />
<meta name="generator" content="Beuth-Toolbox 2.0" />
<meta name="revisiondate" content="2002-05-04" />
<meta name="year" content="2002" />