

<p><span class="Autorenname">Argyle, Michael</span> (1986):<br>
		  K&ouml;rpersprache und Kommunikation, Junfermann Verlag 1986</p>
		  
		  <p><span class="Autorenname">Berg, R. et al.</span> (1987): <br>
		  Netzplantechnik, Verlag industrielle Organisation, Z&uuml;rich 1987</p>
		  
		  <p><span class="Autorenname">B&uuml;hler, Karl E./Hesse, H.</span> (Hrsg) (1997):<br>
			Kommunikation und Perspektivit&auml;t, K&ouml;nigshausen 1997</p>
			
		  <p> <span class="Autorenname">B&uuml;rdek, Bernhard-E.</span> (1975): <br>
			Design-Theorie, Selbstverlag, Stuttgart 1977</p>
			
		  <p> <span class="Autorenname">Buzan, Tony; Buzan, Barry</span> (2002):<br> 
		  Das Mindmap Buch, mvg, 2002</p>
		  
		  <p><span class="Autorenname">Fendrich, Jochem</span> (1985): <br>
		  Unterlagen Produktmamangementschulung, Krups Solingen 1985</p>
		  
		  <p><span class="Autorenname">Geyer, Erich</span> (1987):<br>
		  Kreativit&auml;t im Unternehmen, Verlag moderne Industrie, Landsberg 1987</p>
		  
		  <p> <span class="Autorenname">Gorb, Peter</span> (1987): <br>
		  The business of design management, in: Bernsen, Jens (Ed.): Design Management in Practise, Danish Design Council, Copenhagen, 
		  1987 PG1-PG6</p>
		  
		  <p> <span class="Autorenname">Grillo, Michael </span>(1988): <br>
		  Designablaufmodell, in: VDID extra, Verband Deutscher Industrie Designer, Stuttgart 1988</p>
		  
		  <p> <span class="Autorenname">Hammer, N.</span> (1992): <br>
			M&ouml;glichkeiten und Grenzen der &Uuml;berpr&uuml;fung von Designprodukten durch Okulometrie, Dissertation, 
			Universit&auml;t GH Essen, Verlag Die Blaue Eule, Essen 1992</p>
			
		  <p> <span class="Autorenname">Hammer, N. </span>(1993a): <br>
			Das Management von Designprojekten, Anmerkungen zur Zusammenarbeit mit Designern, in: Designerhandbuch NRW, 
			Design Zentrum NRW, Seite 129-134, Essen 1993</p>
			
		  <p> <span class="Autorenname">Hammer, N.</span> (1993b): Was kostet Design, in: Designerhandbuch NRW, Design Zentrum NRW, 
		  Seite 135-145, Essen 1993</p>
		  
		  <p> <span class="Autorenname">Hammer, N.</span> (1994): <br>
			Das Design von POI/POS-Systemen, Gestaltung und Gestaltungsevaluierung von Benutzeroberfl&auml;chen, in: 
			Proceedings, 	Symposium des Fraunhofer Institutes f&uuml;r Software und Systemtechnik, Dortmund, Sept. 1994</p>
			
		  <p> <span class="Autorenname">Hammer, N.</span> (1995): <br>
		  Testing Design via Eye-Movement Analysis - Perspectives and Problems, ESOMAR Seminar &bdquo;Testing for optimal Design and 
		  Function&ldquo;, Berlin, Februar 1995, S.155-172 (ESOMAR = Europ&auml;ische Gesellschaft f&uuml;r Meinungs- und
		  Marketing-Forschung)</p>
		  
		  <p><span class="Autorenname">Landau, Erika</span> (1969): <br>
		  Psychologie der Kreativit&auml;t, M&uuml;nchen, Basel 1969</p>
		  
		  <p> <span class="Autorenname">Linneweh, Klaus</span> (1973): <br>
		  Kreatives Denken, Karlsruhe 1973</p>
		  
		  <p><span class="Autorenname">Norman, D.A.</span> (1989): <br>
		  Dinge des Alltags, Frankfurt, New York 1989</p>
		  
		  <p><span class="Autorenname">R&uuml;ckle, Horst </span>(1991): <br>
		  K&ouml;rpersprache verstehen und deuten, Niedernhausen 1991</p>
		  
		  <p><span class="Autorenname">Schaude, G&ouml;tz</span> (1995): <br>
		  Kreativit&auml;ts-, Probleml&ouml;sungs- und Pr&auml;sentationstechniken, RKW, Eschborn 1995</p>
		  
		  <p><span class="Autorenname">Schreiber, Dieter</span> (1998):<br>
		  Kreativit&auml;t in der Gestaltung, Forschungsbericht, HDK Halle 1998</p>
		  
		  <p><span class="Autorenname">Schulz von Thun, Friedemann</span> (1992): <br>
		  Miteinander reden, Band 1 u. 2, Rowohlt, Reinbek 1992</p>
		  
		  <p> <span class="Autorenname">Stangl, Anton</span> (1977): <br>
		  Die Sprache des K&ouml;rpers, Knaur 1977</p>
		