<meta name="viewport" content="width=device-width">
<!-- Javascript für die Navigations-MouseOver-Tooltipps -->
<!-- Annährung ans Layout03 von Martin Frehse -->

<script src="../../.inc/js/lib/jquery-1.8.3.js" type="text/javascript"></script>
<script src="../../.inc/js/lib/jquery.tools.min_full.js" type="text/javascript"></script>
<script src="../../.inc/js/lib/jquery.scrollTo-1.4.12.js" type="text/javascript"></script>
<script src="../.inhalt/navpages.js" type="text/javascript"></script>


<script src="../../.inc/js/defaults.js" type="text/javascript"></script>
<script src="pages.js" type="text/javascript"></script>
<script src="chapdefines.js" type="text/javascript"></script>
<script src="../chapters.js" type="text/javascript"></script>
<script src="../defines.js" type="text/javascript"></script>
<script src="../../.inc/js/navifunc.js" type="text/javascript"></script>
<script src="../../.inc/js/besucht.js" type="text/javascript"></script>
<!-- <script src="../../.inc/js/modulename.js" type="text/javascript"></script> -->
<link rel="stylesheet" href="../../.inc/overlib.css">

<!-- Mathjax JS Framework fuer mathematische Formeln -->
<script type="text/javascript" src="../../.inc/mathjax/MathJax.js?config=default"></script>

<!-- neues Javascript für Rollovers etc. -->
<script src="../../.inc/js/vfh.js" type="text/javascript"></script>

<!-- Script/Style fuer neuen AudioPlayer - Florian Kruellke Novmeber 2014  -->
<script src="../../.inc/js/audioplayer.js" type="text/javascript"></script>	
<link rel="stylesheet" type="text/css" media="screen" href="../../.inc/css/audioplayer.css"> 

<!-- Rollovergrafiken für Inhaltsseite laden 
<script type="text/javascript">preloadImages(); </script>
-->
<!-- Bugreport & Feedback -->
<script src="../../.inc/bugfeedback/bugfeedback.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="../../.inc/bugfeedback/bugreport.css" />
<link rel="stylesheet" href="../../.inc/bugfeedback/feedback.css">

<!-- Dynamische Ausgabe von Bearbeitungszeit von Dorian Wojda -->
<script src="../../.inc/js/bearbeitungszeit.js" type="text/javascript"></script>

<!-- Ausgabe von Schlagworten -->
<script src="../../.inc/js/buzzwords.js" type="text/javascript"></script>

<!-- Code highlighting per rainbow.js -->
<script src="../../.inc/js/highlight/rainbow.js" type="text/javascript"></script>
<script src="../../.inc/js/highlight/generic.js" type="text/javascript"></script>
<script src="../../.inc/js/highlight/linenumbers.js" type="text/javascript"></script>
<script src="../../.inc/js/highlight/java.js" type="text/javascript"></script>
<script src="../../.inc/js/highlight/javascript.js" type="text/javascript"></script>
<script src="../../.inc/js/highlight/html.js" type="text/javascript"></script>
<script src="../../.inc/js/highlight/css.js" type="text/javascript"></script>
<link rel="stylesheet" media="screen" href="../../.inc/css/highlight/themes/tricolore.css">

<!-- fancybox -->
<script src="../../.inc/js/lib/fancybox.js" type="text/javascript"></script>
<link rel="stylesheet" media="screen" href="../../.inc/css/fancybox.css">