    <!-- ###################################################################################################### --> 
		<!-- ################################### INCLUDE START -> shell_bottom.inc ################################### --> 
		<!-- ###################################################################################################### --> 
    </div>
  	<!-- ===== INHALT RECHTS ENDE ===== -->
    <div class="clearTheFloats">&nbsp;</div>
    <!-- ===== INHALT RECHTS ENDE ===== --> 
  </div>
  <!-- ===== INHALT ENDE ===== --> 
  
  <!-- ===== FOOTER START ===== -->
  <div id="footerContainer">
    <div id="navBottom" style="">
        <div class="navBottom-yellow-gradient" style=""></div>
        <div class="navBottom-stripes-grey" style=""></div>
        <div id="navBottomInfo">
          <span class="footertext"></span>
        </div>
        <script type="text/javascript">
          document.querySelector(".footertext").innerHTML = copyBeuth;
        </script>
    </div>
  <!-- ===== FOOTER ENDE ===== --> 
</div>
</div>
<!-- UMSCHLIESSENDER CONTAINER #mainContainer_shell ENDE -->

	<!-- ###################################################################################################### --> 
	<!-- ################################### INCLUDE ENDE -> shell_bottom.inc ################################### --> 
	<!-- ###################################################################################################### -->
