<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP2REK" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Prof. Dr. Gudrun Görlitz" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="version" content="1.3" />
<meta name="discipline" content="Labor Online Learning" />
<meta name="creation_time" content="20020701" />
<meta name="learning_time" content="180" />
<meta name="language" content="DE" />
<meta name="keywords" content="Rekursion" />
<meta name="description" content="In diesem Kapitel erklären wir, was Rekursion ist und welche Arten rekursiver Aufrufe es gibt. Rekursion und Iteration werden miteinander verglichen. Wir zeigen, wie der Speicher während der Abarbeitung rekursiver Methoden verwaltet wird." />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="REK" />
<meta name="unit_dir" content="GP2REK" />
<meta name="unit" content="Rekursion" />
<meta name="unit_number" content="08" />
<meta name="pdf_title" content="Rekursion" />
<meta name="generator" content="Beuth-Toolbox 2.0" />
<meta name="revisiondate" content="2002-07-01" />
<meta name="year" content="2002" />