<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP2FXG" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Prof. Dr. Agathe Merceron" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="discipline" content="Medieninformatik Online Bachelor" />
<meta name="creation_time" content="20161219" />
<meta name="learning_time" content="150" />
<meta name="language" content="DE" />
<meta name="keywords" content="JavaFX, Scene Builder, Model View, GUI, Grafische Benutzeroberflächen" />
<meta name="description" content="" />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="FXG" />
<meta name="unit_dir" content="GP2FXG" />
<meta name="unit" content="JavaFX - Grundlagen" />
<meta name="unit_number" content="05" />
<meta name="pdf_title" content="JavaFXGrundlagen" />
<meta name="version" content="1.0" />
<meta name="generator" content="BHT-Toolbox 2.0" />
<meta name="revisiondate" content="2006-08-18" />
<meta name="year" content="2016" />