<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP2EIP" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Prof. Dr. Gudrun Görlitz" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="version" content="1.3" />
<meta name="discipline" content="Medieninformatik Online Bachelor" />
<meta name="creation_time" content="20020405" />
<meta name="learning_time" content="180" />
<meta name="language" content="DE" />
<meta name="keywords" content="JBuilder" />
<meta name="description" content="In dieser ersten Lerneinheit des Moduls Programmieren II wiederholen wir zunächst kurz die wesentlichen Inhalte aus dem Modul Programmieren I. Programmierkenntnisse in der objektorientierten Programmiersprache Java und entsprechende Programmierfertigkeiten aus Programmieren I sind die Voraussetzung für die Bearbeitung des Moduls Programmieren II. Ausserdem wird in dieser Lerneinheit in die integrierte Entwicklungsumgebung Eclipse anhand eines Programmbeispiels eingeführt." />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="EIP" />
<meta name="unit_dir" content="GP2EIP" />
<meta name="unit" content="Einstieg in Programmieren II" />
<meta name="unit_number" content="01" />
<meta name="pdf_title" content="EinstiegInProgrammieren2"/>
<meta name="generator" content="Beuth-Toolbox 2.0" />
<meta name="revisiondate" content="2008-03-14" />
<meta name="year" content="2002" />