<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP2LST" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Prof. Dr. Gudrun Görlitz, Prof. Dr. Agathe Merceron" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="version" content="1.3" />
<meta name="discipline" content="Medieninformatik Online Bachelor" />
<meta name="creation_time" content="20020719" />
<meta name="learning_time" content="180" />
<meta name="language" content="DE" />
<meta name="keywords" content="Listen" />
<meta name="description" content="Verkettete Listen sind nach Reihungen eine der wichtigsten Datenstrukturen, die für die Implementierung umfangreicher Algorithmen benutzt werden. Vor- und Nachteile von verketteten Listen gegenüber Reihungen werden in diesem Kapitel am Beispiel einfacher dynamischer Datenmengen dargestellt. Grundprinzipen und Techniken der Implementierung dynamischer Datenmengen mit Hilfe von Listen werden vorgestellt." />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="LST" />
<meta name="unit_dir" content="GP2LST" />
<meta name="unit" content="Listen" />
<meta name="unit_number" content="10" />
<meta name="pdf_title" content="Listen" />
<meta name="generator" content="Beuth-Toolbox 2.0" />
<meta name="revisiondate" content="2009-10-15" />
<meta name="year" content="2002" />