<meta name="viewport" content="width=device-width, initial-scale=1.0">

<script language="JavaScript" src="../../../_src/.inc/jquery-1.8.3.js" type="text/javascript"></script>
<!-- <script src="../../../_src/.inc/jquery.js" type="text/javascript"></script> -->
<script src="../../../_src/.inc/jquery.tools.min_full.js" type="text/javascript"></script>

<script src="../../../_src/.inc/defaults.js" type="text/javascript"></script>
<script src="../../../_src/.inc/js/modulename.js" type="text/javascript"></script>
<script src="pages.js" type="text/javascript"></script>
<script src="chapdefines.js" type="text/javascript"></script>
<script src="../chapters.js" type="text/javascript"></script>
<script src="../defines.js" type="text/javascript"></script>
<link rel="stylesheet" href="../../../_src/.inc/overlib.css">

<!-- neues Javascript für Rollovers etc. -->
<script src="../../../_src/.inc/vfh.js" type="text/javascript"></script>

<!-- Rollovergrafiken für Inhaltsseite laden 
<script>preloadImages();</script> -->

<!-- Javascript für die Navigations-MouseOver-Tooltipps -->
<!-- Annährung ans Layout03 von Martin Frehse -->

<script src="../.inhalt/navpages.js" type="text/javascript"></script>

<!-- Bugreport & Feedback -->
<script src="../../../_src/.inc/bugfeedback/bugfeedback.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="../../../_src/.inc/bugfeedback/bugreport.css" />

<!-- Dynamische Ausgabe von Bearbeitungszeit von Dorian Wojda -->
<script src="../../../_src/.inc/bearbeitungszeit.js" type="text/javascript"></script>

<!-- Ausgabe von Schlagworten -->
<script src="../../../_src/.inc/buzzwords.js" type="text/javascript"></script>

<script src="../../../_src/.inc/navifunc.js" type="text/javascript"></script>