    <!-- ###################################################################################################### --> 
		<!-- ########################## INCLUDE: SKRIPTE der SHELL -> shell_scripts.inc ############################ --> 
		<!-- ###################################################################################################### -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<script src="../.inc/js/lib/jquery-1.8.3.js" type="text/javascript"></script>
		<script src="../.inc/js/vfh.js" type="text/javascript"></script>
		<script src="shell.js" type="text/javascript"></script>
		<script src="copyright.js" type="text/javascript"></script>
    <!-- ###################################################################################################### --> 
		<!-- ####################### INCLUDE ENDE: SKRIPTE der SHELL -> shell_scripts.inc ########################## --> 
		<!-- ###################################################################################################### --> 
