<meta http-equiv="x-ua-compatible" content="IE=edge" />
<meta name="id" content="VFHGP2AKI" />
<meta name="copyright" content="Beuth Hochschule Berlin. All rights reserved" />
<meta name="author" content="Prof. Dr. Gudrun Görlitz, Prof. Dr. A. Merceron" />
<meta name="contributor" content="Design und Produktion: Labor Online Learning" />
<meta name="version" content="1.3" />
<meta name="discipline" content="Medieninformatik Online Bachelor" />
<meta name="creation_time" content="20020204" />
<meta name="learning_time" content="180" />
<meta name="language" content="DE" />
<meta name="keywords" content="Interface, Abstrakte Klasse" />
<meta name="description" content="" />
<meta name="module_short" content="VFHGP2" />
<meta name="module" content="Grundlagen der Programmierung II" />
<meta name="unit_short" content="AKI" />
<meta name="unit_dir" content="GP2AKI" />
<meta name="unit" content="Abstrakte Klassen und Interfaces" />
<meta name="unit_number" content="03" />
<meta name="pdf_title" content="AbstrakteKlassenUndInterfaces"/>
<meta name="generator" content="Beuth-Toolbox 2.0" />
<meta name="revisiondate" content="2009-09-09" />
<meta name="year" content="2002" />