<input id="textRange" class="audiorange" type="range" min="0" step="1" max="30" value="0">
<section class="audiobutton_leiste">
	<button id="textStart" class="audioButton" type="button" title="Start" style="background-color: #efefef; border: none; float: left;">
		<svg height="20" width="15">
			<polygon points="0,1 0,19 4,19 4,1" style="fill:black;"></polygon>
			<polygon points="4,10 14,2 14,18" style="fill:black;"></polygon>
		</svg>
	</button>
	<button id="textPlay" type="button" title="Play" style="background-color: #efefef; border: none; float: left;">
		<svg style="width: 15px; height: 20px;">
			<polygon points="0,0 0,20 15,10" style="fill:black;"></polygon>
		</svg>
	</button>
	<data id="audiotextTimer" class="audiotextTimer">00:00</data>
	<button id="textPause" type="button" title="Pause" style="background-color: #efefef; border: none; float: left;">
		<svg height="20" width="15">
			<polygon points="1.5,2.0 1.5,18.0 5.5,18.0 5.5,2.0" style="fill:black;"></polygon>
			<polygon points="9.5,2.0 9.5,18.0 13.5,18.0 13.5,2.0" style="fill:black;"></polygon>
		</svg>
	</button>
	<button id="textEnde" type="button" title="Ende" style="background-color: #efefef; border: none; float: left;">
		<svg height="20" width="15">
			<polygon points="0,2.0 0,18.0 10.0,10.0" style="fill:black;"></polygon>
			<polygon points="10.0,1.0 10.0,19.0 14.0,19.0 14.0,1.0" style="fill:black;"></polygon>
		</svg>
	</button>
</section>
<!-- Audio-Include -->