This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./paper.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file paper.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (16 comparisons).
Generating output file paper.acr....done (7 lines written, 0 warnings).
Output written in paper.acr.
Transcript written in paper.alg.
